package:
  name: conda-tools
  version: 0.1

source:
  git_url: ..
  git_rev: master

build:
  number: 1

requirements:
  build:
    - python
  run:
    - python
    - pathlib2   [py<3]

about:
  home: https://github.com/groutr/conda-tools
  license: BSD
